blank_issues_enabled: false
contact_links:
  - name: ‚ùì Questions
    url: https://github.com/SWHL/PreProcessLaTeXFormulaTools/discussions/categories/q-a
    about: Please use the community forum for help and questions regarding PreProcessLaTeXFormulaTools Docs
  - name: üí° Feature requests and ideas
    url: https://github.com/SWHL/PreProcessLaTeXFormulaTools/discussions/new?category=feature-requests
    about: Please vote for and post new feature ideas in the community forum
  - name: üìñ Documentation
    url: https://rapidai.github.io/PreProcessLaTeXFormulaTools/
    about: A great place to find instructions and answers on how to run your custom PreProcessLaTeXFormulaTools.
